// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfettiController from "./confetti_controller"
application.register("confetti", ConfettiController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HorsePhotosController from "./horse_photos_controller"
application.register("horse-photos", HorsePhotosController)

import LocationAutocompleteController from "./location_autocomplete_controller"
application.register("location-autocomplete", LocationAutocompleteController)

import MapController from "./map_controller"
application.register("map", MapController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
